#!/usr/bin/env node
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; //allow node-request to deal with Error: DEPTH_ZERO_SELF_SIGNED_CERT

var
  fs = require('fs'),
  path = require('path'),
  program = require('commander'),
  repl = require('repl'),
  util = require('util'),

  version = require('./package.json').version,
  joolaio = global.joolaio = require('joola.sdk');

var configPath = path.join(__dirname, './config.json');
if (fs.existsSync(configPath)) {
  var config = require(configPath);
  Object.keys(config).forEach(function (key) {
    program[key] = config[key];
  });
}

program
  .version(version)
  .option('-h, --host [http://localhost:8080]', 'Joola host (http://hostname:port)')
  .option('-u, --username [username]', 'username for login with Joola')
  .option('-p, --password [password]', 'password for login with Joola')
  .option('-a, --apitoken [apitoken]', 'APIToken to use instead of username/password')
  .option('-e, --eval [script]', 'javascript to execute and close')
  .option('-f, --file [filename]', 'javascript file to execute and close')
  .option('-g, --gist [url]', 'javascript gist url to execute and close')
  .option('-d, --debug', 'print out debug messages');

program
  .command('get')
  .description('joola get <key>')
  .action(function (key) {
    console.log(key, program[key]);
    process.exit();
  });

program
  .command('set')
  .description('joola set <key> <value>')
  .action(function (key, value) {
    program[key] = value;
    if (!config)
      config = {};
    config[key] = value;
    fs.writeFileSync(configPath, JSON.stringify(config));
    process.exit();
  });

program
  .command('clear')
  .description('joola clear <key>')
  .action(function (key) {
    delete program[key]
    if (config)
      delete config[key];
    fs.writeFileSync(configPath, JSON.stringify(config));
    process.exit();
  });

program.parse(process.argv);

//console.log('joola.cli (' + version + ') starting...');
//console.log('Connecting to Joola @ ' + program.host + '...');

if (program.apitoken) {
  joolaio.init({APIToken: program.apitoken, host: program.host, debug: {enabled: program.debug || false}}, function (err) {
    if (err)
      throw err;
  });
}
else if (program.username && program.password) {
  joolaio.init({host: program.host, debug: {enabled: program.debug || false}}, function (err) {
    if (err)
      throw err;

    joolaio.users.authenticate('joola', program.username, program.password, function (err, token) {
      if (err)
        throw err;
      joolaio.USER = token.user;
      joolaio.TOKEN = token;

    });
  });
}
else {
  console.error('Authentication failed, no login details provided.');
  process.exit();
}

joolaio.events.on('ready', function () {
  startCLI();
});


var startCLI = function () {
  console.log('');

  var self = this;
  ['q', 'exit', 'quit'].forEach(function (key) {
    self.__defineGetter__(key, function () {
      process.exit();
    });
  });

  this.__defineGetter__('help', function () {
    var helptext = {};

    var inspect = joolaio.api.describe;
    if (inspect) {
      Object.keys(inspect).forEach(function (key) {
        var elem = inspect[key];
        helptext[key] = {};
        Object.keys(elem).forEach(function (elemKey) {
          var attribute = elem[elemKey];
          helptext[key][elemKey] = {
            endpoint: attribute.name,
            description: attribute.description,
            params: attribute.inputs
          }
        });
      });
      console.log(util.inspect(helptext, {depth: null, colors: true}));
    }
    else
      console.error(what + ' unknown');
  });

  var prompt = '' + joolaio.USER.username + '@' + program.host.replace('http://', '').replace('https://', '') + '> ';
  if (program.file || program.eval || program.gist)
    prompt = '';
  var _repl = repl.start({
    prompt: prompt,
    input: process.stdin,
    output: process.stdout,
    useGlobal: true,
    eval: function (cmd, context, filename, callback) {
      try {
        var result;
        if (cmd.substring(0, 1) === '(')
          cmd = cmd.substring(1, cmd.length - 2);
        if (cmd.indexOf('joola.') > -1 && cmd.indexOf('(') > -1) {
          var printDocs = false;
          if (cmd.indexOf('joola.query') > -1)
            printDocs = true;
          var fn = function (err, result) {
            if (printDocs && result && result.documents) {
              return callback(err, result.documents);
            }
            return callback(err, result);
          };
          var inject = fn.toString();
          if (cmd.indexOf(',') > -1)
            cmd = cmd.replace(')', ',' + inject + ')');
          else if (cmd.indexOf('()') > -1)
            cmd = cmd.replace(')', inject + ')');
          else
            cmd = cmd.replace(')', ',' + inject + ')');

          cmd = 'try{' + cmd + '}catch(ex){console.log(ex);}';
          eval(cmd);
        }
        else {
          result = eval(cmd);
          return callback(null, result);
        }

      }
      catch (ex) {
        if (typeof callback === 'function')
          return callback(ex);
        else {
          console.error(ex);
        }
      }
    }
  });
  require('repl.history')(_repl, 'joola_repl_history');
  if (program.eval) {
    _repl.eval(program.eval, null, null, function (err, result) {
      if (err)
        throw err;
      console.log(util.inspect(result, {depth: null, colors: true}));
      exit();
    });
  }
  if (program.file) {
    var script = fs.readFileSync(program.file);
    _repl.eval(script.toString('utf8'), null, null, function (err, result) {
      if (err)
        throw err;
      console.log(util.inspect(result, {depth: null, colors: true}));
      exit();
    });
  }
  if (program.gist) {
    var parts = url.parse(program.gist);
    var proto = parts.protocol === 'https:' ? require('https') : require('http');
    proto.get(program.gist, function (res) {
      var script = '';
      res.on('data', function (chunk) {
        script += chunk;
      });
      res.on('end', function () {
        _repl.eval(script, null, null, function (err, result) {
          if (err)
            throw err;
          console.log(util.inspect(result, {depth: null, colors: true}));
          exit();
        });
      });
    });
  }
};